### ISSUE TITLE
FROM email whitelisting isn't working

### ISSUE THREAD

**Issue by lcdservices** [JMAConsulting/biz.jmaconsulting.ode#23]
The FROM email address whitelisting functionality isn't actually working. A review of the code indicates the setting and form to enable that functionality exists, but the email check doesn't actually review the from email addresses to find if there's a match. It only looks at the site domain.

Here's a proposed patch:
https://gist.github.com/lcdservices/ce1f90cf18c42f44c0648acc3de5a58d

Actually, that would need to be conditioned on whether the setting is enabled. Let me know if you want me to file a PR.

**Comment by JoeMurray** [comment]
Edsel, could you QA patch and merge. Also, could you adjust the README.md to indicate on install that the setting can be adjusted if desired, and how to navigate to that page. Please test on jma.staging.ao.

**Comment by lcdservices** [comment]
@Edzelopez It's definitely not working. I did the following:

- enabled the FROM whitelisting option in ODE Settings
- added a FROM email address with a domain different from the site
- went to a contrib page and used that email as the FROM address for receipts

It returned the ODE validation warning instead of accepting it as a valid value.

**Comment by monishdeb** [comment]
Moved to https://lab.civicrm.org/extensions/ode/-/issues/23
