### ISSUE TITLE
Redisplay error message on settings page

### ISSUE THREAD

**Issue by JoeMurray** [JMAConsulting/biz.jmaconsulting.ode#24]
Currently, on install/enable a list of invalid emails is displayed, eg
![2018-10-10_17-06-02](https://user-images.githubusercontent.com/300943/46766889-54df5400-ccb1-11e8-9d7a-8716414a5b24.png)

I believe there is a settings page (see https://github.com/JMAConsulting/biz.jmaconsulting.ode/issues/23) that allows one to choose to allow FROM email address (civicrm/admin/options/from_email_address?reset=1) to be valid in addition to the Org email provided at civicrm/admin/domain?action=update&reset=1. Please redisplay the errors when that page is visited, and document that page in the README.md.

**Comment by monishdeb** [comment]
Moved to https://lab.civicrm.org/extensions/ode/-/issues/24
