### ISSUE TITLE
change session log implementation

### ISSUE THREAD

**Issue by JoeMurray** [JMAConsulting/biz.jmaconsulting.ode#25]
I noticed the following, and think we should likely incorporate
joe@aegir:/var/aegir/platforms/civicrm-dev/vendor/civicrm$ cat biz.jmaconsulting.ode.PATCH 
diff --git a/vendor/civicrm/biz.jmaconsulting.ode/ode.php b/vendor/civicrm/biz.jmaconsulting.ode/ode.php
index f8c080d6d..688841931 100644
--- a/vendor/civicrm/biz.jmaconsulting.ode/ode.php
+++ b/vendor/civicrm/biz.jmaconsulting.ode/ode.php
@@ -329,7 +329,8 @@ function ode_suppressEmails(&$fromEmailAddress, $showNotice) {
     if ($showNotice === 'returnMessage') {
       return array('msg' => $status);
     }
-    $session->setStatus($status, ts('Notice'));
+    // [ML] $session->setStatus($status, ts('Notice'));
+    Civi::log()->info('ODE: ' . $status);
   }
   return NULL;
 }

**Comment by monishdeb** [comment]
Moved to https://lab.civicrm.org/extensions/ode/-/issues/25
